EpicodusChan/Models/Group.cs
using System.Collections.Generic;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EpicodusChan.Models
{
  	public class Group
	  {
		public Group()
		{
			this.Messages = new HashSet<Message>();
		}

		public int GroupId { get; set; }
		public string GroupName { get; set; }
		public string Topic { get; set; }
		public ICollection<Message> Messages { get; set; }

    public static List<Group> GetGroups()
  {
    var apiCallTask = ApiHelper.GetAll("Groups");
    var result = apiCallTask.Result; 

    JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
    List<Group> groupList = JsonConvert.DeserializeObject<List<Group>>(jsonResponse.ToString());

    return groupList; 
  }

  public static Group GetDetails(int id)
    {
      var apiCallTask = ApiHelper.GetGroup(id);
      var result = apiCallTask.Result;

      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      Group group = JsonConvert.DeserializeObject<Group>(jsonResponse.ToString());

      return group;
    }
      public static void Post(Group group)
    {
      string jsonGroup = JsonConvert.SerializeObject(group);
      var apiCallTask = ApiHelper.CreateGroup(jsonGroup);
    }

    public static void Put(Group group)
    {
      string jsonGroup = JsonConvert.SerializeObject(group);
      var apiCallTask = ApiHelper.PutGroup(group.GroupId, jsonGroup);
    }
    
    public static void Delete(int id)
    {
      var apiCallTask = ApiHelper.DeleteGroup(id);
    }

	}
}

EpicodusChan/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EpicodusChan.Models;

namespace EpicodusChan.Controllers
{
  public class GroupsController : Controller
  {
    public IActionResult Index()
    {
      var allGroups = Group.GetGroups();
      return View(allGroups);
    }
    public IActionResult Details(int id)
    {
      var group = Group.GetDetails(id);
      return View(group);
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(Group group)
    {
      Group.Post(group);
      return RedirectToAction("Index");
    }

    public IActionResult Edit(int id)
    {
      var group = Group.GetDetails(id);
      return View(group);
    }

    [HttpPost]
    public IActionResult Edit(Group group)
    {
      Group.Put(group);
      return RedirectToAction("Details", "Groups", new { id = group.GroupId });
    }
    public IActionResult Delete(int id)
    {
      var thisGroup = Group.GetDetails(id);
      return View(thisGroup);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeleteConfirmed(int id)
    {
      Group.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

EpicodusChan/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EpicodusChan.Models;

namespace EpicodusChan.Controllers
{
  public class MessagesController : Controller
  {
    public IActionResult Index()
    {
      var allMessages = Message.GetMessages();
      return View();
    }

  // [HttpGet("/groups/{groupId}/messages/details/{messageId}")]
    public IActionResult Details(int groupId, int messageId)
    {
      var message = Message.GetDetails(groupId, messageId);
      return View(message);
    }

    public IActionResult Create(int groupId)
    {
      ViewBag.groupId = groupId;
      return View();
    }

    [HttpPost]
    public IActionResult Create(int groupId, Message message)
    {
      // message.MessageId = Id;
      Message.CreateMessage(groupId, message);
      return RedirectToAction("Details", "Groups", new { id = groupId});
    }
    public IActionResult Edit(int groupId, int messageId)
    {
      ViewBag.GroupId = groupId;
      var message = Message.GetDetails(groupId, messageId);
      return View(message);
    }

    [HttpPost]
    public ActionResult Edit(int groupId, Message message)
    {
      Message.PutMessage(groupId, message);
      return RedirectToAction("Index");
    }
    public IActionResult Delete(int groupId, int messageId)
    {
      var thisMessage = Message.GetDetails(groupId, messageId);
      return View(thisMessage);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int groupId, int messageId)
    {
      Message.DeleteMessage(groupId, messageId);
      return RedirectToAction("Details", "Groups", new { id = groupId });
    }
  }
}

EpicodusChan/Views/Groups/Create.cshtml
<h1>Create a New Group: </h1>

@model EpicodusChan.Models.Group

@using(Html.BeginForm())
{
  <div class="form-group">
    <p>Group Name:</p>
    @Html.TextBoxFor(model => model.GroupName, new {@class="form-control"})
  </div>
  <div class="form-group">
    <p>Topic:</p>
    @Html.TextBoxFor(model => model.Topic, new {@class="form-control"})
  </div>
  <button type="submit" class="btn btn-dark btn-lg">Add Group</button>
}

EpicodusChan/Views/Groups/Delete.cshtml
@{
  Layout = "_Layout";
}

@model EpicodusChan.Models.Group

<h2>Are you sure you want to delete this group?</h2>

@Html.DisplayNameFor(model => model.GroupId): @Html.DisplayFor(model => model.GroupId)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

EpicodusChan/Views/Groups/Details.cshtml
<h1>@Model.GroupName</h1>
<h2>Topic: @Model.Topic</h2>
<hr>

@foreach( var message in Model.Messages)
{
  <h4> @Html.ActionLink($"{@message.Title}", "Details", "Messages", new { groupId = Model.GroupId, messageId = message.MessageId})</h4>
  <div>
    <p>
      @message.Entry
    </p>
    <p>@message.UserName</p>
  </div>
}

@Html.ActionLink("Add Message", "Create", "Messages", new {groupId = Model.GroupId}, new {@class="btn btn-dark btn-lg"})

@Html.ActionLink("Edit", "Edit", new {id = Model.GroupId}, new {@class="btn btn-success btn-lg"})

@Html.ActionLink("Delete this Group", "Delete", new {id = Model.GroupId}, new {@class="btn btn-danger btn-lg"})

EpicodusChan/Views/Groups/Edit.cshtml
@{
    ViewData["Group"] = "Edit";
}

@model EpicodusChan.Models.Group

<h1>Edit Group:</h1>

@* <form action="/Groups/Details/@(Model.GroupId)" method="post">
  <label for="GroupId">Group ID:</label>
  <input id="GroupId" name="GroupId" type="text" value="@(Model.GroupId)">
  <label for="GroupName">Group Name:</label>
  <input id="GroupName" name="GroupName" type="text" value="@(Model.GroupName)">
  <label for="Topic">Topic</label>
  <input id="Topic" name="Topic" type="text" value="@(Model.Topic)">
  <button type="submit">Go!</button>
</form> *@

@using(Html.BeginForm())
{
  <input type="hidden" name="groupId" value="@Model.GroupId">

  <div class="form-group">
    <p>Group Name:</p>
    @Html.TextBoxFor(model => model.GroupName, new {@class="form-control"})
  </div>

  <div class="form-group">
    <p>Topic:</p>
    @Html.TextBoxFor(model => model.Topic, new {@class="form-control"})
  </div>
  <button type="submit" class="btn btn-dark btn-lg">Edit Group</button>
}

<a href="/Groups/Details/@(Model.GroupId)"><p>Return to Groups</p></a>

EpicodusChan/Views/Groups/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Select a chat Group:</h1>

@foreach(Group group in Model)
{
  <li>@Html.ActionLink($"{group.GroupName}", "Details", new { id = group.GroupId })</li>
}

<a href="/groups/create">
    <button class="btn btn-dark btn-lg">Create Group</button>
</a>